Repository NSK-Transportation/transportation-platform, pull requests merged in 2024-09, with the labels that each got.

#51 Fix sale tickets
  src/app/@types/index.d.ts
  src/app/styles/root.css
  src/pages/home/components/informationPanel/InformationPanel.tsx
  src/pages/home/components/informationPanel/child/seatInfoItem/SeatInfoItem.tsx
  src/pages/home/components/informationPanel/child/seatInfoItem/seatInfoPlace/SeatInfoPlace.tsx
  src/pages/home/components/informationPanel/child/seatInfoItem/seatInfoPrice/SeatInfoPrice.tsx
  src/pages/home/components/informationPanel/child/seatInfoItem/seatInfoWay/SeatInfoWay.tsx
  src/pages/home/components/mainPanel/MainPanel.store.tsx
  src/pages/home/components/mainPanel/child/saleTicket/SaleTicket.tsx
  src/pages/home/components/mainPanel/child/saleTicket/passengerInfoItem/PassengerInfoItem.tsx
  src/pages/home/components/mainPanel/child/saleTicket/returnInfoItem/ReturnInfoItem.tsx
  src/pages/home/components/mainPanel/child/saleTicket/seatMainItem/SeatMainItem.tsx
  src/pages/home/components/mainPanel/child/saleTicket/wayMainList/WayMainList.tsx
  src/pages/home/components/mainPanel/child/saleTicket/wayMenu/WayMenu.tsx
  src/pages/home/components/mainPanel/child/saleTicket/wayPayment/WayPayment.tsx
  src/shared/api/axiosInstance.ts
  src/shared/api/mutations.ts
  src/shared/api/queries.ts
  src/shared/ui/divider/Divider.module.scss
  src/shared/ui/divider/Divider.tsx
Labels: fix

#52 Fix main store
  src/pages/home/components/mainPanel/MainPanel.store.tsx
  src/pages/home/components/mainPanel/child/index.ts
  src/pages/home/components/mainPanel/child/plusBaggage/PlusBaggage.store.tsx
  src/pages/home/components/mainPanel/child/refundTicket/RefundTicket.store.tsx
  src/pages/home/components/mainPanel/child/saleTicket/SaleTicket.store.tsx
  src/pages/home/components/mainPanel/child/saleTicket/passengerInfoItem/PassengerInfoItem.tsx
  src/pages/home/components/mainPanel/child/wayManagement/WayManagement.store.tsx
Labels: fix

#53 Fix main store
  src/pages/home/components/index.ts
  src/pages/home/components/informationPanel/InformationPanel.tsx
  src/pages/home/components/informationPanel/child/seatInfoItem/seatInfoPlace/SeatInfoPlace.tsx
  src/pages/home/components/informationPanel/child/seatInfoItem/seatInfoPrice/SeatInfoPrice.tsx
  src/pages/home/components/informationPanel/child/seatInfoItem/seatInfoWay/SeatInfoWay.tsx
  src/pages/home/components/mainPanel/MainPanel.store.tsx
  src/pages/home/components/mainPanel/child/plusBaggage/PlusBaggage.store.tsx
  src/pages/home/components/mainPanel/child/plusBaggage/PlusBaggage.tsx
  src/pages/home/components/mainPanel/child/plusBaggage/enterDataPassenger/EnterDataPassenger.tsx
  src/pages/home/components/mainPanel/child/plusBaggage/infoAboutPassenger/InfoAboutPassenger.tsx
  src/pages/home/components/mainPanel/child/plusBaggage/infoAboutTicket/InfoAboutTicket.tsx
  src/pages/home/components/mainPanel/child/refundTicket/RefundTicket.store.tsx
  src/pages/home/components/mainPanel/child/refundTicket/RefundTicket.tsx
  src/pages/home/components/mainPanel/child/refundTicket/enterDataPassenger/EnterDataPassenger.tsx
  src/pages/home/components/mainPanel/child/refundTicket/infoAboutPassenger/InfoAboutPassenger.tsx
  src/pages/home/components/mainPanel/child/refundTicket/infoAboutRefund/InfoAboutRefund.tsx
  src/pages/home/components/mainPanel/child/refundTicket/infoAboutTicket/InfoAboutTicket.tsx
  src/pages/home/components/mainPanel/child/saleTicket/SaleTicket.store.tsx
  src/pages/home/components/mainPanel/child/saleTicket/SaleTicket.tsx
  src/pages/home/components/mainPanel/child/saleTicket/passengerInfoItem/PassengerInfoItem.tsx
  src/pages/home/components/mainPanel/child/saleTicket/returnInfoItem/ReturnInfoItem.tsx
  src/pages/home/components/mainPanel/child/saleTicket/seatMainItem/SeatMainItem.tsx
  src/pages/home/components/mainPanel/child/saleTicket/wayMainList/WayMainList.tsx
  src/pages/home/components/mainPanel/child/saleTicket/wayMenu/WayMenu.tsx
  src/pages/home/components/mainPanel/child/saleTicket/wayPayment/WayPayment.tsx
  src/pages/home/components/mainPanel/child/wayManagement/WayManagement.store.tsx
  src/pages/home/components/mainPanel/child/wayManagement/filterMenu/FilterMenu.tsx
Labels: fix

#56 Add way management store
  src/app/@types/index.d.ts
  src/pages/home/components/headerPanel/HeaderPanel.module.scss
  src/pages/home/components/mainPanel/child/wayManagement/WayManagement.store.tsx
  src/pages/home/components/mainPanel/child/wayManagement/WayManagement.tsx
  src/pages/home/components/mainPanel/child/wayManagement/filterMenu/FilterMenu.tsx
  src/pages/home/components/mainPanel/child/wayManagement/managementList/ManagementList.tsx
  src/pages/home/components/mainPanel/child/wayManagement/managementTable/ManagementTable.tsx
  src/pages/home/components/mainPanel/child/wayManagement/wayInformation/WayInformation.tsx
  src/pages/home/components/mainPanel/child/wayManagement/wayManagementItem/WayManagementItem.tsx
  src/shared/api/queries.ts
  src/shared/ui/modal/Modal.module.scss
  src/shared/ui/modal/Modal.tsx
Labels: component

#55 Fix sale tickets
  src/app/@types/index.ts
  src/app/styles/root.css
  src/pages/home/components/informationPanel/InformationPanel.store.tsx
  src/pages/home/components/informationPanel/child/seatInfoItem/SeatInfoItem.tsx
  src/pages/home/components/informationPanel/child/seatInfoItem/seatInfoPlace/SeatInfoPlace.tsx
  src/pages/home/components/informationPanel/child/seatInfoItem/seatInfoWay/SeatInfoWay.tsx
  src/pages/home/components/informationPanel/child/seatInfoItem/ticketInfo/TicketInfo.config.tsx
  src/pages/home/components/informationPanel/child/seatInfoItem/ticketInfo/TicketInfo.tsx
  src/pages/home/components/mainPanel/child/index.ts
  src/pages/home/components/mainPanel/child/saleTicket/SaleTicket.store.tsx
  src/pages/home/components/mainPanel/child/saleTicket/SaleTicket.tsx
  src/pages/home/components/mainPanel/child/saleTicket/passengerInfoItem/PassengerInfoItem.form.tsx
  src/pages/home/components/mainPanel/child/saleTicket/passengerInfoItem/PassengerInfoItem.tsx
  src/pages/home/components/mainPanel/child/saleTicket/passengerInfoItem/PassengerInfoItem.utils.tsx
  src/pages/home/components/mainPanel/child/saleTicket/returnInfoItem/ReturnInfoItem.tsx
  src/pages/home/components/mainPanel/child/saleTicket/seatMainItem/SeatMainItem.tsx
  src/pages/home/components/mainPanel/child/saleTicket/wayMenu/WayMenu.tsx
  src/pages/home/components/mainPanel/child/saleTicket/wayPayment/WayPayment.tsx
  src/shared/ui/customCalendar/CustomCalendar.tsx
  src/shared/ui/input/Input.module.scss
  src/shared/ui/input/Input.tsx
  src/shared/ui/tooltip/Tooltip.tsx
  src/shared/utils/getCapitalizeFirstLetter.ts
  src/shared/utils/getResolveKeyPath.ts
  src/shared/utils/getUniqueId.ts
  src/shared/utils/index.ts
Labels: fix

#58 Add UI country select
  src/app/@types/index.ts
  src/pages/home/components/informationPanel/child/seatInfoItem/ticketInfo/TicketInfo.config.tsx
  src/pages/home/components/informationPanel/child/seatInfoItem/ticketInfo/TicketInfo.tsx
  src/pages/home/components/mainPanel/child/saleTicket/SaleTicket.store.tsx
  src/pages/home/components/mainPanel/child/saleTicket/passengerInfoItem/PassengerInfoItem.config.tsx
  src/pages/home/components/mainPanel/child/saleTicket/passengerInfoItem/PassengerInfoItem.tsx
  src/pages/home/components/mainPanel/child/saleTicket/passengerInfoItem/PassengerInfoItem.utils.tsx
  src/shared/ui/countrySelect/CountrySelect.module.scss
  src/shared/ui/countrySelect/CountrySelect.tsx
  src/shared/ui/index.ts
  src/shared/ui/input/Input.module.scss
  src/shared/ui/input/Input.tsx
  src/shared/ui/select/Select.module.scss
  src/shared/ui/select/Select.tsx
  src/shared/utils/getFormatPhoneNumber.ts
  src/shared/utils/index.ts
Labels: ui

#60 Add UI dropdown
  src/app/@types/index.ts
  src/pages/home/components/mainPanel/child/saleTicket/SaleTicket.store.tsx
  src/pages/home/components/mainPanel/child/saleTicket/wayMenu/WayMenu.tsx
  src/shared/ui/customCalendar/CustomCalendar.scss
  src/shared/ui/dropdownStation/DropdownStation.module.scss
  src/shared/ui/dropdownStation/DropdownStation.tsx
  src/shared/ui/index.ts
  src/shared/ui/inputGroup/InputGroup.module.scss
Labels: ui

#61 Fix sale ticket
  src/app/@types/index.ts
  src/pages/home/components/informationPanel/child/seatInfoItem/ticketInfo/TicketInfo.config.tsx
  src/pages/home/components/informationPanel/child/seatInfoItem/ticketInfo/TicketInfo.tsx
  src/pages/home/components/mainPanel/child/saleTicket/SaleTicket.store.tsx
  src/pages/home/components/mainPanel/child/saleTicket/passengerInfoItem/PassengerInfoItem.config.tsx
  src/pages/home/components/mainPanel/child/saleTicket/passengerInfoItem/PassengerInfoItem.tsx
  src/pages/home/components/mainPanel/child/saleTicket/passengerInfoItem/PassengerInfoItem.utils.tsx
  src/pages/home/components/mainPanel/child/saleTicket/seatMainItem/SeatMainItem.tsx
  src/pages/home/components/mainPanel/child/saleTicket/wayMenu/WayMenu.tsx
  src/pages/home/components/mainPanel/child/saleTicket/wayPayment/WayPayment.tsx
  src/shared/api/mutations.ts
  src/shared/ui/countrySelect/CountrySelect.tsx
  src/shared/ui/customCalendar/CustomCalendar.scss
  src/shared/ui/customCalendar/CustomCalendar.tsx
  src/shared/ui/dropdownStation/DropdownStation.module.scss
  src/shared/ui/dropdownStation/DropdownStation.tsx
  src/shared/ui/input/Input.module.scss
  src/shared/ui/input/Input.tsx
  src/shared/ui/typography/Typography.tsx
Labels: fix

#62 Fix aside panel
  src/app/styles/root.css
  src/pages/home/components/asidePanel/AsidePanel.module.scss
  src/pages/home/components/asidePanel/AsidePanel.store.tsx
  src/pages/home/components/asidePanel/AsidePanel.tsx
  src/shared/assets/icons/index.ts
  src/shared/ui/button/Button.module.scss
  src/shared/ui/button/Button.tsx
Labels: fix

#63 Fix refund ticket
  src/app/@types/index.ts
  src/pages/home/components/mainPanel/child/refundTicket/RefundTicket.store.tsx
  src/pages/home/components/mainPanel/child/refundTicket/RefundTicket.tsx
  src/pages/home/components/mainPanel/child/refundTicket/enterDataPassenger/EnterDataPassenger.tsx
  src/pages/home/components/mainPanel/child/refundTicket/infoAboutPassenger/InfoAboutPassenger.config.tsx
  src/pages/home/components/mainPanel/child/refundTicket/infoAboutPassenger/InfoAboutPassenger.tsx
  src/pages/home/components/mainPanel/child/refundTicket/infoAboutRefund/InfoAboutRefund.tsx
  src/pages/home/components/mainPanel/child/refundTicket/infoAboutTicket/InfoAboutTicket.config.tsx
  src/pages/home/components/mainPanel/child/refundTicket/infoAboutTicket/InfoAboutTicket.tsx
  src/shared/api/queries.ts
  src/shared/assets/icons/index.ts
  src/shared/ui/alert/Alert.module.scss
  src/shared/ui/alert/Alert.tsx
  src/shared/ui/index.ts
Labels: fix

#64 Fix auth page
  src/pages/auth/Auth.store.tsx
  src/pages/auth/Auth.tsx
  src/shared/ui/input/Input.module.scss
  src/shared/ui/time/Time.tsx
Labels: fix

#65 Fix sale ticket
  package-lock.json
  package.json
  src/app/@types/index.ts
  src/pages/home/components/informationPanel/child/seatInfoItem/seatInfoWay/SeatInfoWay.tsx
  src/pages/home/components/mainPanel/child/saleTicket/SaleTicket.tsx
  src/pages/home/components/mainPanel/child/saleTicket/passengerInfoItem/PassengerInfoItem.config.tsx
  src/pages/home/components/mainPanel/child/saleTicket/wayMainItem/WayMainItem.tsx
  src/pages/home/components/mainPanel/child/saleTicket/wayMenu/WayMenu.tsx
  src/pages/home/components/mainPanel/child/saleTicket/wayPayment/PassengerInfoScreen.tsx
  src/pages/home/components/mainPanel/child/saleTicket/wayPayment/WayPayment.tsx
  src/server/database/data.json
  src/shared/api/axiosInstance.ts
  src/shared/api/queries.ts
Labels: fix
